### ISSUE TITLE
Add comparison to at(1) and batch(1)

### ISSUE THREAD

**Issue by dbohdan** [leahneukirchen/nq#28]
First, thanks for writing this tool!  It's an elegant design.

I think people who find it for the first time may wonder how it's different from POSIX `at` and `batch`.  It could be useful to preempt their questions in the readme.  Somebody asked on Hacker News, and I posted a [five-point comparison](https://news.ycombinator.com/item?id=25924401) based on my best understanding of both `nq` and `at`/`batch`.  Feel free to use the text of that comment under your choice of license.

**Comment by leahneukirchen** [comment]
Thanks, I added that with minor editing.
