### ISSUE TITLE
add comparison to task-spooler

### ISSUE THREAD

**Issue by niol** [leahneukirchen/nq#31]
https://vicerveza.homeunix.net/~viric/soft/ts/ is very similar. It would be nice to have an overview of the differences against it.

**Comment by m040601** [comment]
funny thing, I was just browsing this repo 1 hour ago, and had t**he exact same thought.**

Anothe upvote for adding the comparison with task spooler

Speciially since you already have a very nicely written one with at/batch.

**Comment by leahneukirchen** [comment]
Well, if someone is familar with it, feel free to provide one.

But I don't want to end up writing the ultimate queue tool comparison.

**Comment by leahneukirchen** [comment]
Merged.
