### ISSUE TITLE
nq: When spawning many jobs, all nq processes stuck with high cpu load, no work done

### ISSUE THREAD

**Issue by ltning** [leahneukirchen/nq#37]
We're using `nq` to process batch files in a neat, orderly fashion. For the most part, this works awesomely (thanks!). However, we sometimes get a burst of jobs to process, causing many dozen `nq` processes/jobs to be started (with the same `$NQDIR`), and at some point - I'm not certain when - work stops being done while all `nq` processes get stuck consuming significant CPU.

`truss` on a random one gives, with a few seconds interval, the following in repeated fashion:
```
flock(5,LOCK_EX)                                 = 0 (0x0)                                                                                       
close(5)                                         = 0 (0x0)                                                                                       
lseek(3,0x0,SEEK_SET)                            = 0 (0x0)                                                                                       
getdirentries(3,"\M^A\f\^C\0\0\0\0\0\^A\0\0\0\0\0"...,4096,{ 0x0 }) = 4088 (0xff8)                                                               
openat(3,",177d4c573b4.8614",O_RDWR,00)          = 5 (0x5)                                                                                       
flock(5,LOCK_EX|LOCK_NB)                         ERR#35 'Resource temporarily unavailable'                                                       
```
with the file it refers to being an earlier (completed) job in the same `$NQDIR`.

I'm not sure what to do to debug this in a meaningful fashion. I'm trying to come up with a reasonable reproduction scenario but so far it has eluded me. When this happens, we end up with a bunch of files in the `$NQDIR` without any content beyond the leading `exec` line.

Suggestions?

**Comment by ltning** [comment]
Some additional detail: It seems like all hung/cpu-gobbling processes are trying to access the same older file.

Additionally, only (in the test I'm currently running) about 1/3 of the processes are actually gobbling CPU, the remainder sits idle. It seems the same ones gobbling the CPU also show up when doing an `fstat` on the file in question, as it lists the same number of nq processes trying to access the file.

Finally - something that seems to work around the problem is using `nc -c` - I have not been able to reproduce when using this option (and starting with an empty `NQDIR`.

**Comment by ltning** [comment]
While using `nc -l`, a reproduction scenario seems to look like this:

- `for i in {1..1000} ; do nq -cq sleep 1 ; done`
  - A big number to have something to work with
  - Nothing bad will happen
- `while true ; do pkill sleep ; sleep 0.05 ; done`
  - Makes the sleep exit with rc>0, causing queue file to be left in place
  - Let this run for a couple seconds, watch CPU load suddenly spike
- List nq processes, `truss -p <pid>` on one of the CPU-hogging processes
- Unlink the file it's poking
- Watch CPU load go down, queue processing continues

Perhaps this information helps - and apologies for the wall of text.

**Comment by leahneukirchen** [comment]
I can't reproduce this on Linux, so I need more details about your OS.

**Comment by ltning** [comment]
Ah sorry, completely forgot. FreeBSD 12.2, and also 13-BETA1 (didn't get around to upgrading to BETA2 or whatever the current state of affairs is).

**Comment by leahneukirchen** [comment]
Ok, I can reproduce this. For some reason the again: loop is run too often, because the non-blocking flock call fails but the blocking one is immediately successful.

**Comment by ltning** [comment]
Sounds promising.
Somewhat related: Is there an upper limit imposed by `nq` on how many files can be in `$NQDIR`? Other than filesystem limitations, practical concerns, etc. Will having a large number (several thousands) of old files there be a problem?

**Comment by leahneukirchen** [comment]
truss output with timestamps:

```
0.000019276 lseek(3,0x0,SEEK_SET)                = 0 (0x0)
0.000191086 getdirentries(3,"\M-,\^C\0\0\0\0\0\0\^A\0\0\0\0\0"...,4096,{ 0x0 }) = 4080 (0xff0)
0.000024864 openat(3,",177e495946c.80375",O_RDWR,00) = 5 (0x5)
0.003381435 flock(5,LOCK_EX|LOCK_NB)             ERR#35 'Resource temporarily unavailable'
1.241440462 flock(5,LOCK_EX)                     = 0 (0x0)
0.004825473 close(5)                             = 0 (0x0)
0.005419124 lseek(3,0x0,SEEK_SET)                = 0 (0x0)
0.000063695 getdirentries(3,"\M-,\^C\0\0\0\0\0\0\^A\0\0\0\0\0"...,4096,{ 0x0 }) = 4080 (0xff0)
0.000097777 openat(3,",177e495946c.80375",O_RDWR,00) = 5 (0x5)
0.005145905 flock(5,LOCK_EX|LOCK_NB)             ERR#35 'Resource temporarily unavailable'
1.472615654 flock(5,LOCK_EX)                     = 0 (0x0)
0.004810667 close(5)                             = 0 (0x0)
0.000020673 lseek(3,0x0,SEEK_SET)                = 0 (0x0)
0.000092190 getdirentries(3,"\M-,\^C\0\0\0\0\0\0\^A\0\0\0\0\0"...,4096,{ 0x0 }) = 4080 (0xff0)
0.003993524 openat(3,",177e495946c.80375",O_RDWR,00) = 5 (0x5)
0.003644597 flock(5,LOCK_EX|LOCK_NB)             ERR#35 'Resource temporarily unavailable'
0.970510497 flock(5,LOCK_EX)                     = 0 (0x0)
0.003623924 close(5)                             = 0 (0x0)
0.000049727 lseek(3,0x0,SEEK_SET)                = 0 (0x0)
0.000048889 getdirentries(3,"\M-,\^C\0\0\0\0\0\0\^A\0\0\0\0\0"...,4096,{ 0x0 }) = 4080 (0xff0)
0.000022350 openat(3,",177e495946c.80375",O_RDWR,00) = 5 (0x5)
0.003317741 flock(5,LOCK_EX|LOCK_NB)             ERR#35 'Resource temporarily unavailable'
1.243692704 flock(5,LOCK_EX)                     = 0 (0x0)
0.004264230 close(5)                             = 0 (0x0)
0.000029334 lseek(3,0x0,SEEK_SET)                = 0 (0x0)
0.004278197 getdirentries(3,"\M-,\^C\0\0\0\0\0\0\^A\0\0\0\0\0"...,4096,{ 0x0 }) = 4080 (0xff0)
0.000032686 openat(3,",177e495946c.80375",O_RDWR,00) = 5 (0x5)
0.003716953 flock(5,LOCK_EX|LOCK_NB)             ERR#35 'Resource temporarily unavailable'
1.158880249 flock(5,LOCK_EX)                     = 0 (0x0)
0.004515099 close(5)                             = 0 (0x0)
```

So for some reason, even tho the lock could be acquired it needs to acquire it again, which should never happen I think...

**Comment by leahneukirchen** [comment]
I did not test nq with many (>1000) ,-files, essentially every nq process checks that all previous ,-files are unlocked. So it's somehow quadratic in that sense.

**Comment by leahneukirchen** [comment]
Ok, I see how this happens now: when two processes (or more, then it's easier) iterate over the list of files to check for locks "meet each other", both restart at the beginning, synchonizing even more. And the closer this happens, the more CPU load it takes.

**Comment by ltning** [comment]
Anything further I can do? Short of providing a patch, which I'm woefully unqualified for..

**Comment by leahneukirchen** [comment]
Try removing the `rewinddir` call, which ensures it will only lock each file once. I *think* this still should be correct, as "earlier" files should not appear at this point.

**Comment by leahneukirchen** [comment]
I have a more robust fix, but it will take a bit to implement.

**Comment by ltning** [comment]
I'll test it on my laptop when I get home, and let you know. Am looking forward to the "more robust fix".
Curious though - is this a FreeBSD issue, since it doesn't happen on Linux?

**Comment by leahneukirchen** [comment]
No, but the FreeBSD scheduler seems to make this come up earlier somehow.

**Comment by leahneukirchen** [comment]
Please try the `betterwait` branch.

**Comment by ltning** [comment]
That seems to work (`betterwait`). Queued up 1000 jobs, seemed to work just fine.

Then tried with 10.000, which worked fine but made my laptop sweat quite badly - until it wedged (mouse pointer and all) about 1/3 way through processing the queue. I guess `nq` is not to blame there :)

**Comment by ltning** [comment]
Bit too quick there .. I'm still seeing the same behaviour; many of the `nq` processes get stuck on the same job file. The job file in question is a completed job, exited with stauts 0. On my laptop it seems harder to trigger, but in our production environment it happens quite reliably when the queue size is significant (>500 jobs).

**Comment by leahneukirchen** [comment]
@duncaen proposed another fix, i added it to `betterwait`, please try.

**Comment by ltning** [comment]
Apologies for my tardiness, I'll test this as soon as I'm able to set aside time to do it properly. Thank you for the efforts.

We've worked around it in production by using `-c` and copying the job file as the last thing we do.

Would be outrageous to ask if `nq` could be taught how to rename the job file upon (successful or otherwise) completion?

**Comment by leahneukirchen** [comment]
`nq` in the current design can't rename the job, as it only starts a job but never knows it's finished.

**Comment by ltning** [comment]
Finally got around to testing again. It's clearly less susceptible to this issue now, but it's still fairly straight forward to reproduce:

`c=0; while [ $c -lt 5000 ] ; do /root/nq/nq sleep 0.05 ; c=$((c+1)) ; done`

Then watching `pgrep nq|wc -l`. During this particular run, it is now stuck at 9772.

Truss output (this rushes by at high speed, repeatedly):
```
lseek(3,0x0,SEEK_SET)				 = 0 (0x0)
getdirentries(3,"\M-d\M-+\^E\0\0\0\0\0\^A\0\0\0\0"...,4096,{ 0x0 }) = 4096 (0x1000)
openat(3,",1782c0a6973.44287",O_RDWR,00)	 = 5 (0x5)
flock(5,LOCK_EX|LOCK_NB)			 ERR#35 'Resource temporarily unavailable'
flock(5,LOCK_EX)				 = 0 (0x0)
close(5)					 = 0 (0x0)
lseek(3,0x0,SEEK_SET)				 = 0 (0x0)
getdirentries(3,"\M-d\M-+\^E\0\0\0\0\0\^A\0\0\0\0"...,4096,{ 0x0 }) = 4096 (0x1000)
openat(3,",1782c0a6973.44287",O_RDWR,00)	 = 5 (0x5)
flock(5,LOCK_EX|LOCK_NB)			 ERR#35 'Resource temporarily unavailable'
flock(5,LOCK_EX)				 = 0 (0x0)
close(5)					 = 0 (0x0)
lseek(3,0x0,SEEK_SET)				 = 0 (0x0)
getdirentries(3,"\M-d\M-+\^E\0\0\0\0\0\^A\0\0\0\0"...,4096,{ 0x0 }) = 4096 (0x1000)
openat(3,",1782c0a6973.44287",O_RDWR,00)	 = 5 (0x5)
flock(5,LOCK_EX|LOCK_NB)			 ERR#35 'Resource temporarily unavailable'
flock(5,LOCK_EX)				 = 0 (0x0)
close(5)					 = 0 (0x0)
lseek(3,0x0,SEEK_SET)				 = 0 (0x0)
getdirentries(3,"\M-d\M-+\^E\0\0\0\0\0\^A\0\0\0\0"...,4096,{ 0x0 }) = 4096 (0x1000)
openat(3,",1782c0a6973.44287",O_RDWR,00)	 = 5 (0x5)
```

Checking that file shows the job is completed:
```
$ cat ,1782c0a6973.44287 
exec /root/nq/nq sleep 0.05


[exited with status 0.]
```

Deleting this file lets it continue for a bit, until it gets stuck again - this time at 9692.

Top shows
```
44572 ltning        1  24    0    10M  2100K lockf    5   0:19   9.28% nq
44473 ltning        1  25    0    10M  2100K lockf   11   0:19   9.25% nq
44536 ltning        1  25    0    10M  2100K lockf    5   0:19   9.14% nq
44560 ltning        1  24    0    10M  2100K lockf   11   0:19   9.13% nq
44542 ltning        1  25    0    10M  2100K lockf   10   0:19   9.11% nq
44458 ltning        1  24    0    10M  2100K lockf    7   0:19   9.06% nq
.....
.....
```

Is it even reasonable to expect that this should work? On the other hand, while this is a synthetic test, it does happen frequently in real world usage - and it isn't (despite our attempts to educate to the contrary) unusual that the users of our system end up enqueueing at least several hundred jobs in a very short span of time.

**Comment by leahneukirchen** [comment]
Are you sure you updated the checkout? It should use LOCK_SH now.

**Comment by ltning** [comment]
> Are you sure you updated the checkout? It should use LOCK_SH now.

Yeah, and I should have seen that straight away from the `truss` output.

**Comment by leahneukirchen** [comment]
The problem went away due to use of LOCK_SH.
