### ISSUE TITLE
Simultaneously running certain amount of jobs (i.e. "batching")

### ISSUE THREAD

**Issue by dumblob** [leahneukirchen/nq#42]
It seems nq is meant to serialize all single jobs enqueued in the given queue. How could one easily achieve utilization of all N cores in case there are N+ jobs to be enqued and all of them are CPU-intensive?

Note, I can't simply spawn N separate queues because each job will take different time to finish and thus I'll quickly end up with some cores still maxed out but others already finished with their queues.

**Comment by leahneukirchen** [comment]
You can do that e.g. with a fifo and my other tool https://github.com/leahneukirchen/xe with `-j8` or so.

**Comment by dumblob** [comment]
Sounds good, thanks!
