### ISSUE TITLE
nq does not serialize commands from different users

### ISSUE THREAD

**Issue by dikay0** [leahneukirchen/nq#43]
I installed nq on Ubuntu 20.04 . 'apt list nq' reports:
nq/focal,now 0.3.1-3 amd64 [installed]
I use nq to make sure that the GPU of a multi-user machine is accessed by only a single tensorflow (machine learning) process at a time. To this end, I created a world-writable directory /var/spool/nqdir and 'export NQDIR=/var/spool/nqdir' in /etc/bash.bashrc . Users are taught to start their jobs with 'nq command'. 
This works fine as long as a user starts multiple jobs; these are indeed serialized. However today I saw that two processes, from different users, were running at the same time, and both crashed since the GPU memory is insufficient for both. Both users had used nq, and their logfiles were present in $NQDIR .
Is it a permission issue? Or is nq not supposed to work across several users who use the same NQDIR? How could that be solved? Using 'umask'? If this is a known problem it should be mentioned in the documentation; likewise for a workaround if it exists. Thanks!

**Comment by leahneukirchen** [comment]
Both users need to be able to open the file for writing, was that the case?

**Comment by dikay0** [comment]
no, the file permissions are e.g.
-rw------- 1 dikay    dikay        98 Dec 15 17:15 ,17dbec90fe6.1752043

Ok so the files must be writable by everyone ... this is not always practical but here (university) the users know each other, and cooperate.
What are my options to make the files writable? is that something that depends on the permissions of $NQDIR? Or is it a 'umask' setting?

**Comment by leahneukirchen** [comment]
yeah, you can change the umask when running nq. if the users are not in overlapping groups, you need to use umask 000.

but nq always uses 0600 permissions, so you need to change that first (line 271). I'm pondering whether to change that.

**Comment by leahneukirchen** [comment]
(Note that you should lock down the NQDIR permissions then.)

**Comment by dikay0** [comment]
Thanks! Sounds like I have to recompile nq. 
Permissions of NQDIR are currently drwxrwxrwx which is certainly not optimal. drwxrwxrwt should be more sensible IIUC.
Is it possible to have a world-writable file (for nq to lock across users) that is not world-readable (since logfiles are ultimately private)? Guess I'll have to try it out (and which umask is that?).
It would be great if you could document this multi-user issue, and suggest how to best deal with it. Thanks again!

**Comment by leahneukirchen** [comment]
Please test the `umask` branch. It should work with +t too.

**Comment by leahneukirchen** [comment]
I changed the code to only require opening for reading.

**Comment by leahneukirchen** [comment]
If your logfiles are private, you should redirect them somewhere safe. With +w anyone can overwrite them instead...

A umask of 002 should work even with disjoint groups.

**Comment by leahneukirchen** [comment]
Since both processes can use the GPU, they probably share group video or something?

**Comment by dikay0** [comment]
Thanks for the umask branch! I installed it and will have an eye on it.
The GPU in this specific machine (NVidia RTX3090)  has nothing actually to do with graphics or video (similar as GPUs can be used for mining bitcoins); it is used as a computing accelerator for AlphaFold (https://en.wikipedia.org/wiki/AlphaFold).  AlphaFold can calculate what the structure of a protein looks like; this is interesting since proteins are the main players - besides genes - in living systems, and we would like to understand how they function. Since proteins have tens of thousands of atoms, a lot of memory is needed on the GPU. And that memory may not be enough for two jobs running concurrently. That's why we need to serialize all calculations, no matter if they are queued by one or several users.

**Comment by leahneukirchen** [comment]
yeah, but usually direct access to "video" (even it doesn't display anything) hardware is gated by some group.

**Comment by dikay0** [comment]
I see what you mean; there may be some setup of /dev/nvidia* or so during installation of AlphaFold which removes the requirement of adding users to a video group or similar. But I'm not aware of what is done in that respect.

**Comment by leahneukirchen** [comment]
Did you get a chance to test this?

**Comment by dikay0** [comment]
The "umask" branch has been working well for me since you created it.

**Comment by leahneukirchen** [comment]
Merged, thanks.
